name: Feature Request
description: 新機能の提案
title: "[Feature] "
labels: ["enhancement", "triage"]
assignees:
  - omasaaki

body:
  - type: markdown
    attributes:
      value: |
        新機能の提案ありがとうございます。
        
  - type: textarea
    id: problem
    attributes:
      label: 解決したい問題
      description: この機能要求の背景となる問題を説明してください
      placeholder: 現在、〜という場面で困っています
    validations:
      required: true
      
  - type: textarea
    id: solution
    attributes:
      label: 提案する解決策
      description: どのような機能があれば問題が解決されるか説明してください
      placeholder: 〜という機能があれば解決できると考えています
    validations:
      required: true
      
  - type: textarea
    id: alternatives
    attributes:
      label: 代替案
      description: 他に考えられる解決方法があれば記載してください
      
  - type: textarea
    id: additional
    attributes:
      label: 追加コンテキスト
      description: この機能要求に関する追加情報があれば記載してください
      
  - type: dropdown
    id: priority
    attributes:
      label: 優先度
      description: この機能の優先度はどの程度ですか？
      options:
        - Low - あると便利
        - Medium - そこそこ重要
        - High - とても重要
        - Critical - 必須機能
    validations:
      required: true