version: '3.8'

x-postgres-common: &postgres-common
  environment:
    POSTGRES_DB: pgsd_test
    POSTGRES_USER: test_user
    POSTGRES_PASSWORD: test_pass
    POSTGRES_INITDB_ARGS: --encoding=UTF-8 --locale=en_US.utf8
  volumes:
    - ./init:/docker-entrypoint-initdb.d:ro
  healthcheck:
    test: ["CMD-SHELL", "pg_isready -U test_user -d pgsd_test"]
    interval: 5s
    timeout: 5s
    retries: 10
    start_period: 10s
  labels:
    com.pgsd.test: "true"
  networks:
    - pgsd-test

services:
  postgres-13:
    <<: *postgres-common
    image: postgres:13-alpine
    container_name: pgsd_test_pg13
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: pgsd_test
      POSTGRES_USER: test_user
      POSTGRES_PASSWORD: test_pass
      POSTGRES_INITDB_ARGS: --encoding=UTF-8 --locale=en_US.utf8
      PG_VERSION: "13"

  postgres-14:
    <<: *postgres-common
    image: postgres:14-alpine
    container_name: pgsd_test_pg14
    ports:
      - "5434:5432"
    environment:
      POSTGRES_DB: pgsd_test
      POSTGRES_USER: test_user
      POSTGRES_PASSWORD: test_pass
      POSTGRES_INITDB_ARGS: --encoding=UTF-8 --locale=en_US.utf8
      PG_VERSION: "14"

  postgres-15:
    <<: *postgres-common
    image: postgres:15-alpine
    container_name: pgsd_test_pg15
    ports:
      - "5435:5432"
    environment:
      POSTGRES_DB: pgsd_test
      POSTGRES_USER: test_user
      POSTGRES_PASSWORD: test_pass
      POSTGRES_INITDB_ARGS: --encoding=UTF-8 --locale=en_US.utf8
      PG_VERSION: "15"

  postgres-16:
    <<: *postgres-common
    image: postgres:16-alpine
    container_name: pgsd_test_pg16
    ports:
      - "5436:5432"
    environment:
      POSTGRES_DB: pgsd_test
      POSTGRES_USER: test_user
      POSTGRES_PASSWORD: test_pass
      POSTGRES_INITDB_ARGS: --encoding=UTF-8 --locale=en_US.utf8
      PG_VERSION: "16"

networks:
  pgsd-test:
    name: pgsd_test_network
    driver: bridge

volumes:
  pg13_data:
  pg14_data:
  pg15_data:
  pg16_data: